api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--messaging
        value: '{{ .Env.MESSAGING_SERVICEBUSENDPOINT }}'
      - name: connectionstrings--orders
        value: '{{ .Env.STORAGE_BLOBENDPOINT }}'
  template:
    containers:
      - image: {{ .Image }}
        name: orders-api
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: MESSAGING_HOST
            value: '{{ .Env.MESSAGING_SERVICEBUSHOSTNAME }}'
          - name: MESSAGING_URI
            value: '{{ .Env.MESSAGING_SERVICEBUSENDPOINT }}'
          - name: ORDERS_URI
            value: '{{ .Env.STORAGE_BLOBENDPOINT }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: OrderStorage__StorageDirectory
            value: data/orders
          - name: ConnectionStrings__messaging
            secretRef: connectionstrings--messaging
          - name: ConnectionStrings__orders
            secretRef: connectionstrings--orders
        volumeMounts:
          - volumeName: orders-storage
            mountPath: /data
    volumes:
      - name: orders-storage
        storageType: AzureFile
        storageName: {{ .Env.ORDERS_STORAGE_VOLUME_NAME }}
    scale:
      minReplicas: 1
tags:
  azd-service-name: orders-api
  aspire-resource-name: orders-api
