# =============================================================================
# Azure Container Apps Manifest - Web Application
# =============================================================================
#
# Purpose:
#   Defines the Azure Container Apps deployment configuration for the eShop
#   Web Application (Blazor frontend). This template is processed by Azure
#   Developer CLI (azd) during deployment, with Go template variables
#   ({{ .Env.* }}) resolved at runtime.
#
# Service:
#   eShop.Web.App - Blazor Server frontend for the eShop application
#
# Dependencies:
#   - Orders API (orders-api) - Backend REST API for order operations
#   - Azure Container Registry - Container image storage
#   - Application Insights - Telemetry and monitoring
#
# Template Variables:
#   {{ .Env.* }}              - Environment variables from azd environment
#   {{ .Image }}              - Container image URI (resolved by azd)
#   {{ targetPortOrDefault }} - Port helper function (default: 8080)
#
# Security:
#   - Uses User-Assigned Managed Identity for Azure resource access
#   - Sticky sessions enabled for Blazor Server SignalR connections
#   - HTTPS enforced (allowInsecure: false)
#
# Documentation:
#   - Container Apps: https://learn.microsoft.com/azure/container-apps/
#   - Blazor Server: https://learn.microsoft.com/aspnet/core/blazor/hosting-models
#   - API Reference: https://learn.microsoft.com/azure/templates/microsoft.app/containerapps
#
# Author: Evilazaro
# Last Modified: 2026-01-26
# =============================================================================

# API version for Azure Container Apps resource provider
api-version: 2024-02-02-preview

# Azure region for deployment (inherited from azd environment)
location: {{ .Env.AZURE_LOCATION }}

# -----------------------------------------------------------------------------
# Identity Configuration
# -----------------------------------------------------------------------------
# User-Assigned Managed Identity enables secure, passwordless authentication
# to Azure services (Container Registry, Key Vault)
identity:
  type: UserAssigned
  userAssignedIdentities:
    "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}": {}

properties:
  # Container Apps Environment ID (shared compute environment)
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}

  # ---------------------------------------------------------------------------
  # Application Configuration
  # ---------------------------------------------------------------------------
  configuration:
    # Revision mode: 'single' = only one active revision at a time
    activeRevisionsMode: single

    # .NET runtime-specific settings
    runtime:
      dotnet:
        # Enables automatic Data Protection key management across replicas
        # Required for Blazor Server to maintain authentication state
        autoConfigureDataProtection: true

    # -------------------------------------------------------------------------
    # Ingress Configuration
    # -------------------------------------------------------------------------
    # Exposes the web app externally with HTTP ingress
    ingress:
      external: true                          # Publicly accessible endpoint
      targetPort: {{ targetPortOrDefault 8080 }}  # Container listening port
      transport: http                         # Protocol (http/http2/tcp)
      allowInsecure: false                    # Require HTTPS (TLS termination at ingress)

      # -----------------------------------------------------------------------
      # Sticky Sessions (Session Affinity)
      # -----------------------------------------------------------------------
      # IMPORTANT: Required for Blazor Server applications
      # Blazor Server uses SignalR WebSockets for real-time communication.
      # Sticky sessions ensure all requests from a user route to the same
      # replica, maintaining the SignalR circuit connection.
      stickySessions:
        affinity: sticky

    # -------------------------------------------------------------------------
    # Container Registry Authentication
    # -------------------------------------------------------------------------
    # Uses Managed Identity to pull images (no registry credentials needed)
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}

    # -------------------------------------------------------------------------
    # Secrets Configuration
    # -------------------------------------------------------------------------
    # Sensitive values stored securely, referenced by containers via secretRef
    secrets:
      # Application Insights connection for distributed tracing
      - name: applicationinsights-connection-string
        value: "{{ .Env.TELEMETRY_APPINSIGHTSCONNECTIONSTRING }}"

  # ---------------------------------------------------------------------------
  # Container Template
  # ---------------------------------------------------------------------------
  template:
    containers:
      - image: {{ .Image }}   # Resolved by azd to full ACR image URI
        name: web-app

        # ---------------------------------------------------------------------
        # Environment Variables
        # ---------------------------------------------------------------------
        env:
          # --- Identity Configuration ---
          # Client ID for Managed Identity (used by Azure SDKs)
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}

          # --- ASP.NET Core Configuration ---
          # Enable forwarded headers for proper HTTPS handling behind load balancer
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          # HTTP port binding (Kestrel)
          - name: HTTP_PORTS
            value: "{{ targetPortOrDefault 0 }}"

          # --- Service Discovery (Orders API) ---
          # Direct service URLs for API communication
          # Note: Uses internal Container Apps Environment domain for service-to-service calls
          - name: ORDERS_API_HTTP
            value: http://orders-api.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: ORDERS_API_HTTPS
            value: https://orders-api.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}

          # --- OpenTelemetry Configuration ---
          # Enable detailed event and exception logging for distributed tracing
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          # Retry strategy for OTLP export failures
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory

          # --- .NET Aspire Service Discovery ---
          # These environment variables are used by .NET Aspire's service discovery
          # Format: services__<service-name>__<scheme>__<index>
          - name: services__orders-api__http__0
            value: http://orders-api.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__orders-api__https__0
            value: https://orders-api.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}

          # --- Secret References ---
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            secretRef: applicationinsights-connection-string

    # -------------------------------------------------------------------------
    # Scaling Configuration
    # -------------------------------------------------------------------------
    # Define min/max replicas for autoscaling behavior
    # Note: Blazor Server apps may need more replicas due to persistent connections
    # TODO: Consider adding scale rules based on HTTP concurrency
    scale:
      minReplicas: 5  # Minimum instances for high availability

# -----------------------------------------------------------------------------
# Resource Tags
# -----------------------------------------------------------------------------
# Tags for resource identification and azd service mapping
tags:
  azd-service-name: web-app       # Maps to azd service definition
  aspire-resource-name: web-app   # .NET Aspire resource identifier
