using System.ComponentModel.DataAnnotations;

namespace eShop.Orders.API.Models;

/// <summary>
/// Represents an order in the eShop system.
/// </summary>
/// <remarks>
/// This model is used for both API requests/responses and data validation.
/// All properties include data annotations for automatic model validation.
/// </remarks>
public sealed class Order
{
    /// <summary>
    /// Gets or sets the unique identifier for the order.
    /// </summary>
    /// <remarks>
    /// This ID should be generated by the system and is required for tracking purposes.
    /// </remarks>
    [Required(ErrorMessage = "Order ID is required")]
    [StringLength(50, MinimumLength = 1, ErrorMessage = "Order ID must be between 1 and 50 characters")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the order date and time in UTC.
    /// </summary>
    /// <remarks>
    /// All dates should be stored and transmitted in UTC to avoid timezone issues.
    /// </remarks>
    [Required(ErrorMessage = "Order date is required")]
    public DateTime Date { get; set; }

    /// <summary>
    /// Gets or sets the quantity of items ordered.
    /// </summary>
    /// <remarks>
    /// Quantity must be at least 1. Maximum is bounded by Int32.MaxValue for practical limits.
    /// </remarks>
    [Required(ErrorMessage = "Quantity is required")]
    [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1")]
    public int Quantity { get; set; }

    /// <summary>
    /// Gets or sets the total amount for the order in the system's base currency.
    /// </summary>
    /// <remarks>
    /// Total is calculated as quantity * unit price and must be positive.
    /// Precision is limited to 2 decimal places for currency representation.
    /// </remarks>
    [Required(ErrorMessage = "Total is required")]
    [Range(0.01, double.MaxValue, ErrorMessage = "Total must be greater than 0")]
    public decimal Total { get; set; }

    /// <summary>
    /// Gets or sets the order confirmation or customer message.
    /// </summary>
    /// <remarks>
    /// This field typically contains order notes, confirmation messages, or special instructions.
    /// </remarks>
    [Required(ErrorMessage = "Message is required")]
    [StringLength(500, MinimumLength = 1, ErrorMessage = "Message must be between 1 and 500 characters")]
    public string Message { get; set; } = string.Empty;
}