api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http2
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: applicationinsights-connection-string
        value: '{{ .Env.AZURE_APPLICATION_INSIGHTS_CONNECTION_STRING }}'
      - name: connectionstrings--messaging
        value: '{{ .Env.MESSAGING_SERVICEBUSENDPOINT }}'
  template:
    containers:
      - image: {{ .Image }}
        name: orders-api
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: AZURE_CLIENT_ID
            value: ""
          - name: AZURE_TENANT_ID
            value: 0e2ff29e-431a-420b-8a46-c6f39106927b
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            secretRef: applicationinsights-connection-string
          - name: ConnectionStrings__Messaging
            secretRef: connectionstrings--messaging
    scale:
      minReplicas: 5
tags:
  azd-service-name: orders-api
  aspire-resource-name: orders-api
